// Authentication Actions
export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTH_REQUEST_LOGIN = 'AUTH_REQUEST_LOGIN';
export const AUTH_REQUEST_REGISTER = 'AUTH_REQUEST_REGISTER';
export const AUTH_REQUEST_VALIDATE = 'AUTH_REQUEST_VALIDATE';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Canvas Actions
export const CANVAS_SAVING = 'CANVAS_SAVING';
export const CANVAS_SAVE_REQUEST = 'CANVAS_SAVE_REQUEST';
export const CANVAS_SAVE_SUCCESS = 'CANVAS_SAVE_SUCCESS';
export const CANVAS_SAVE_FAIL = 'CANVAS_SAVE_FAIL';

// Doodle Actions
export const DOODLES_FETCHING = 'DOODLE_FETCHING';
export const DOODLES_REQUEST_FETCH = 'DOODLES_REQUEST_FETCH';
export const DOODLES_FETCH_SUCCESS = 'DOODLE_FETCH_SUCCESS';
export const DOODLES_FETCH_FAIL = 'DOODLE_FETCH_FAIL';

export const DOODLES_DELETING = 'DOODLES_DELETING';
export const DOODLES_REQUEST_DELETE = 'DOODLES_REQUEST_DELETE';
export const DOODLES_DELETE_SUCCESS = 'DOODLES_DELETE_SUCCESS';
export const DOODLES_DELETE_FAIL = 'DOODLES_DELETE_FAIL';
