// Authentication Actions
export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTH_REQUEST_LOGIN = 'AUTH_REQUEST_LOGIN';
export const AUTH_REQUEST_REGISTER = 'AUTH_REQUEST_REGISTER';
export const AUTH_REQUEST_VALIDATE = 'AUTH_REQUEST_VALIDATE';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Doodle Actions
export const DOODLE_SAVING = 'DOODLE_SAVING';
export const DOODLE_SAVE_REQUEST = 'DOODLE_SAVE_REQUEST';
export const DOODLE_SAVE_SUCCESS = 'DOODLE_SAVE_SUCCESS';
export const DOODLE_SAVE_FAIL = 'DOODLE_SAVE_FAIL';

export const DOODLES_FETCHING = 'DOODLE_FETCHING';
export const DOODLES_REQUEST_FETCH = 'DOODLES_REQUEST_FETCH';
export const DOODLES_FETCH_SUCCESS = 'DOODLE_FETCH_SUCCESS';
export const DOODLES_FETCH_FAIL = 'DOODLE_FETCH_FAIL';
