export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTH_REQUEST_LOGIN = 'AUTH_REQUEST_LOGIN';
export const AUTH_REQUEST_REGISTER = 'AUTH_REQUEST_REGISTER';
export const AUTH_REQUEST_VALIDATE = 'AUTH_REQUEST_VALIDATE';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT = 'LOGOUT';
