version: 2.1
jobs: 
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo npm install -g n
      - run: sudo n stable
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm test
