version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: circleci/mongo:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run lint
      - run: 
          environment:
            PORT: "8080"
            SECRET_KEY: "shhh"
            API_LOCK: "123"
            TEST_MONGODB_URI: "mongodb://localhost/doodleit_test"
          command: npm test